# Generated by Django 4.0.3 on 2022-09-14 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_rename_listing_comment_post_remove_listing_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ForeignKey(default='id', on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
    ]
