# Generated by Django 4.0.3 on 2022-09-14 12:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_comment_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='comments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auctions.comment'),
        ),
    ]
