# Generated by Django 4.0.3 on 2022-09-14 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_alter_comment_post_alter_listing_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='comments',
        ),
    ]
